# -*- coding: utf-8 -*-
"""Cópia de extracao de imagens astro

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PHsAXpQadkS0p9sP6UFG_iTfL16tVGjK
"""

import requests
import ipaddress
from time import sleep

#NASA
nasa=[]
for i in range(1,18):
    nasa.append(f"https://images-api.nasa.gov/search?q=galaxies&page={i}")
for i in range(1,66):
    nasa.append(f"https://images-api.nasa.gov/search?q=stars&page={i}")
for i in range(1,73):
    nasa.append(f"https://images-api.nasa.gov/search?q=planets&page={i}")
for i in range(1,11):
    nasa.append(f"https://images-api.nasa.gov/search?q=black%20hole&page={i}")

#EUROPEAN SOUTHERN OBSERVATORY
eso=[
      "https://www.eso.org/public/images/archive/category/stars/",
      "https://www.eso.org/public/images/archive/category/360pano/",
      "https://www.eso.org/public/images/archive/category/alma/",
      "https://www.eso.org/public/images/archive/category/apex/",
      "https://www.eso.org/public/images/archive/category/chile/",
      "https://www.eso.org/public/images/archive/category/cosmology/",
      "https://www.eso.org/public/images/archive/category/elt/",
      "https://www.eso.org/public/images/archive/category/eso-supernova/",
      "https://www.eso.org/public/images/archive/category/exoplanets/",
      "https://www.eso.org/public/images/archive/category/fulldome/",
      "https://www.eso.org/public/images/archive/category/galaxies/",
      "https://www.eso.org/public/images/archive/category/galaxyclusters/",
      "https://www.eso.org/public/images/archive/category/illustrations/",
      "https://www.eso.org/public/images/archive/category/lasilla/",
      "https://www.eso.org/public/images/archive/category/nebulae/",
      "https://www.eso.org/public/images/archive/category/paranal/",
      "https://www.eso.org/public/images/archive/category/peopleandevents/",
      "https://www.eso.org/public/images/archive/category/premises/",
      "https://www.eso.org/public/images/archive/category/blackholes/",
      "https://www.eso.org/public/images/archive/category/solarsystem/",
      "https://www.eso.org/public/images/archive/category/starclusters/",
      "https://www.eso.org/public/images/archive/category/surveytelescopes/"
    ]

for i in range(2,16):
    eso.append(f"https://www.eso.org/public/images/archive/category/stars/list/{i}/")
for i in range(2,11):
    eso.append(f"https://www.eso.org/public/images/archive/category/360pano//list/{i}/")
for i in range(2,35):
    eso.append(f"https://www.eso.org/public/images/archive/category/alma//list/{i}/")
for i in range(2,5):
    eso.append(f"https://www.eso.org/public/images/archive/category/apex//list/{i}/")
for i in range(2,8):
    eso.append(f"https://www.eso.org/public/images/archive/category/chile//list/{i}/")
for i in range(2,5):
    eso.append(f"https://www.eso.org/public/images/archive/category/cosmology//list/{i}/")
for i in range(2,17):
    eso.append(f"https://www.eso.org/public/images/archive/category/elt//list/{i}/")
for i in range(2,13):
    eso.append(f"https://www.eso.org/public/images/archive/category/eso-supernova//list/{i}/")
for i in range(2,6):
    eso.append(f"https://www.eso.org/public/images/archive/category/exoplanets//list/{i}/")
for i in range(2,5):
    eso.append(f"https://www.eso.org/public/images/archive/category/fulldome//list/{i}/")
for i in range(2,15):
    eso.append(f"https://www.eso.org/public/images/archive/category/galaxies//list/{i}/")
for i in range(2,4):
    eso.append(f"https://www.eso.org/public/images/archive/category/galaxyclusters//list/{i}/")
for i in range(2,32):
    eso.append(f"https://www.eso.org/public/images/archive/category/illustrations//list/{i}/")
for i in range(2,31):
    eso.append(f"https://www.eso.org/public/images/archive/category/lasilla//list/{i}/")
for i in range(2,12):
    eso.append(f"https://www.eso.org/public/images/archive/category/nebulae//list/{i}/")
for i in range(2,70):
    eso.append(f"https://www.eso.org/public/images/archive/category/paranal//list/{i}/")
for i in range(2,52):
    eso.append(f"https://www.eso.org/public/images/archive/category/peopleandevents//list/{i}/")
for i in range(2,16):
    eso.append(f"https://www.eso.org/public/images/archive/category/premises//list/{i}/")
for i in range(2,5):
    eso.append(f"https://www.eso.org/public/images/archive/category/blackholes//list/{i}/")
for i in range(2,13):
    eso.append(f"https://www.eso.org/public/images/archive/category/solarsystem//list/{i}/")
for i in range(2,5):
    eso.append(f"https://www.eso.org/public/images/archive/category/starclusters//list/{i}/")
for i in range(2,5):
    eso.append(f"https://www.eso.org/public/images/archive/category/surveytelescopes//list/{i}/")

from random import randint

def gen_ips():
    network=ipaddress.IPv4Network("192.168.1.0/24")
    hosts=[]
    for host in network.hosts():
        hosts.append(host)
    return hosts
def scraping_data():
    dados=[]
    x=0
    y=0
    for data in nasa+eso:
        host=hosts[y]
        network=ipaddress.IPv4Network(host)
        dados.append(requests.get(data).content)
        x+=1
        if x==8:
            y+=1
        sleep(randint(1,3))
    return dados

hosts=gen_ips()

dados=scraping_data()

from bs4 import BeautifulSoup
imgs=[]
#APÓS, BUSCAR IMAGENS NOS LINKS
for dado in dados:
  soup=BeautifulSoup(dado, 'html.parser')
  infos=soup.find_all('a',href=True)
  for info in infos:
    if '.json' in info or '.jpg' in info:
      imgs.append(info)

imgs

